### ISSUE TITLE
what‘s the workaround if I haven't  'PTB corpus LDC99T42'

### ISSUE THREAD

**Issue by SeekPoint** [jgung/semantic-role-labeling#4]

**Comment by jgung** [comment]
Unfortunately, I'm not aware of any open PropBank corpora. https://github.com/propbank/propbank-release provides PropBank annotations, but you need the corresponding corpora to use them.

Alternatively, if you have your own dataset, you can load it with https://github.com/jgung/semantic-role-labeling#training-with-other-data
